### ISSUE TITLE
Make the code PEP8 compliant 

### ISSUE THREAD

**Issue by agarwalrounak** [fossology/atarashi#50]
According to the [code guidelines](https://github.com/fossology/atarashi/blob/master/CONTRIBUTING.md#code-guidelines), it should follow the PEP8 coding style but the code doesn't follow PEP8 standards. 
Thus, make the codebase PEP8 compliant.

**Comment by GMishx** [comment]
The code is actually PEP8 compliant. I guess you are confused with the indentation here.

Since atarashi is under FOSSology project group, we follow 2 space indentation instead of 4 (as recommended in PEP8). Maybe you can add that to the guideline.

**Comment by GMishx** [comment]
Closing as it is irrelevant.
