### ISSUE TITLE
Run the evaluator command without any 'similarity' parameter

### ISSUE THREAD

**Issue by hastagAB** [fossology/atarashi#61]
# Description 
The Evaluator commands are set for both two parameters i.e `agent_name` and `similarity` but some agents runs without similarity type also.

Example: for `tfidf`agent there are three commands :

1. With cosine similarity : `atarashi -a tfidf -s CosineSim /path/to/file.c`
2. With Score similarity : `atarashi -a tfidf -s ScoreSim /path/to/file.c`
3. Without any similarity : `atarashi -a tfidf /path/to/file.c`

The evaluator covers the first two cases and not the third one. The same goes for other agents.

# How to fix
1. Goto the [getCommand](https://github.com/fossology/atarashi/blob/master/atarashi/evaluator/evaluator.py#L45) function of the [evaluator](https://github.com/fossology/atarashi/tree/master/atarashi/evaluator)
2. Write separate conditions as desired or manipulate the existing ones.
3. Test and verify if it's working.

**Comment by Kaushl2208** [comment]
Hey, @hastagAB this issue seems nice. Can I work on it?

**Comment by hastagAB** [comment]
Yes Please, Go Ahead! 👍

> Hey, @hastagAB this issue seems nice. Can I work on it?

Yes Please, Go Ahead! 👍
