### ISSUE TITLE
Pandas error at run: pandas.errors.ParserError

### ISSUE THREAD

**Issue by moonblood2** [fossology/atarashi#67]
<img width="1055" alt="Screen Shot 2020-04-02 at 13 50 05" src="https://user-images.githubusercontent.com/6603643/78211760-df8cc200-74e8-11ea-93fa-cd1e0b672ab7.png">
I got this error after I ran `atarashi -l . -a DLD lib/`

**Comment by GMishx** [comment]
Hello @moonblood2 ,

Did you check the help for atarashi? It says
```
  -l PROCESSEDLICENSELIST, --processedLicenseList PROCESSEDLICENSELIST
                        Specify the location of processed license list file
```

The flag `-l` requires a **processed license list file**, but in your command you are sending `.`.

Please try to provide the actual location of file (can be located at your `site-packages/atarashi/data/licenses/processedLicenses.csv` if installed from PyPi or at `atarashi/data/licenses/processedLicenses.csv`once you build project from source) or you can omit the parameter all together to read from default location.

Also, atarashi currently can not scan a whole folder at one go, so please provide a single file to scan.
