### ISSUE TITLE
List Index Out of Range 

### ISSUE THREAD

**Issue by codeakki** [fossology/atarashi#85]
### When Running atarashi -a {Any agent } -s {Similarities} following error produce:
![image](https://user-images.githubusercontent.com/76440986/113169569-5c20c080-9263-11eb-8009-e3c8cfcb482f.png)

Take a reference from here#80 

### Steps To Reproduce
--> Previously  @Aman-Codes  make changes in [atarahii.py file #L83 ](https://github.com/fossology/atarashi/blob/master/atarashi/atarashii.py#L83)
->which was working fine but after [This PR](https://github.com/fossology/atarashi/pull/83) it again started creating the same error 
->  or I think we need to implement the scan function inside the scan function like [[here](https://github.com/fossology/atarashi/blob/master/atarashi/agents/cosineSimNgram.py#L88)] or update the atarashii.py file

**Comment by GMishx** [comment]
It is working for me:
![image](https://user-images.githubusercontent.com/18077542/113242910-9de75080-92cf-11eb-829e-77fce0c417a6.png)

Also, the line where you are getting the error does not exists:
https://github.com/fossology/atarashi/blob/50f1d7ade90d66cc26b1a781d8aef93961a95876/atarashi/libs/commentPreprocessor.py#L42

Can you please check you are using the latest code?

**Comment by codeakki** [comment]
@GMishx  I tried re-installing Atarashi and now it is giving this error
![image](https://user-images.githubusercontent.com/76440986/113247519-d6d7f300-92d8-11eb-8729-ee6ebf9d99ba.png)
Showing me this error

**Comment by GMishx** [comment]
Try editing the source and dump the exception:
https://github.com/fossology/atarashi/blob/50f1d7ade90d66cc26b1a781d8aef93961a95876/atarashi/atarashii.py#L182-L183

It can be because of many causes.
